// 기본 URL Get
GET http://localhost:3000/ HTTP/1.1
###

// ⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇Users관련
//회원가입 -완료!
POST http://localhost:3000/api/signup HTTP/1.1
Content-Type: application/json; charset=utf-8

{
  "email": "testdddsdd@naver.com",
  "name": "테스트용",
  "password": "test123",
  "confirmPassword": "test123"
}

###
//로그인 -완료
POST http://localhost:3000/api/login  HTTP/1.1
Content-Type: application/json; charset=utf-8

{
  "email": "fortest456@naver.com",
  "password": "test456"
}

###
//내 정보 조회 -완료
GET  http://localhost:3000/api/myinfo HTTP/1.1
Content-Type: application/json; charset=utf-8

###
//비밀번호 수정 -완료
PUT http://localhost:3000/api/myinfo HTTP/1.1
Content-Type: application/json; charset=utf-8

{
  "email": "fortest456@naver.com",
  "password": "test123",
  "newPassword": "test456"
}

###
//회원정보 삭제 - 완료
DELETE  http://localhost:3000/api/myinfo HTTP/1.1
Content-Type: application/json; charset=utf-8

{
  "email": "fortestsad456@naver.com",
  "password": "test123"
}

###
//로그아웃 -완료
POST  http://localhost:3000/api/logout HTTP/1.1
Content-Type: application/json; charset=utf-8


//⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇ Products 관련
###
//상품 등록 - 완료
POST  http://localhost:3000/api/products HTTP/1.1
Content-Type: application/json; charset=utf-8

{
  "title": "감자",
  "content": "담백하고 맛있습니다"
}

###
//상품 전체 조회 - 완료
GET  http://localhost:3000/api/products HTTP/1.1
Content-Type: application/json; charset=utf-8

###
//상품 상세 조회 - 완료
GET  http://localhost:3000/api/products/17 HTTP/1.1
Content-Type: application/json; charset=utf-8

###
//상품 정보 수정
PUT http://localhost:3000/api/products/20 HTTP/1.1
Content-Type: application/json; charset=utf-8

{
  "title": "맛있는 감귤",
  "content": "겨울에 먹으면 더 맛있네요",
  "status": "SOLD_OUT"
}

###
//상품 정보 삭제
DELETE  http://localhost:3000/api/products/17 HTTP/1.1
Content-Type: application/json; charset=utf-8